
# 错误处理

Rust将错误分为两种：
1. 可恢复性错误，即不会导致系统崩溃的错误，如用户操作错误
2. 不可恢复错误，该错误通常是全局性或者系统性的错误，会导致系统崩溃，例如数组越界访问

对于可恢复性错误，Rust使用`Result<T, E>`处理，对于不可恢复性错误，Rust使用`panic!`处理

## panic

### panic使用

```rust
fn main() {
    panic!("crash and burn");
}
```

有两种处理panic的方式：
- 栈展开：使用`RUST_BACKTRACE=1 cargo run`可以展开调用栈，最近调用的函数在最上面。为了开启栈展开，程序需要开启debug。
- 直接终止：如果担心debug模式程序太大，直接终止程序，可以如下配置
  ```rust
    [profile.release]
    panic = 'abort'
  ```

如果main进程panic，程序终止。如果子进程panic，子进程终止而主进程不会。

### expect与unwarp

- 如果返回值是OK，提取枚举中的值，如果返回值是Err，panic
- expect比unwarp多一个错误信息参数
- expect和unwarp也可以对Option使用

```rust
use std::net::IpAddr;
let home: IpAddr = "127.0.0.1".parse().unwrap();
let home: IpAddr = "127.0.0".parse().expect("格式错误"); // panic
let v = Some(1).unwrap();
let v :i32 = None.unwrap(); // panic
let v :i32 = None.expect("aaa"); // panic
```

### 何时使用panic

1. 确定程序没问题时，如`let home: IpAddr = "127.0.0.1".parse().unwrap();`，ip地址肯定没错
2. 示例、测试等需要快速搭建代码的场景
3. 可能导致更严重错误时，如后续代码功能受影响


## Result

### Result使用

Result定义
```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => panic!("Problem opening the file: {:?}", other_error),
        },
    };
}

```


### 错误传播

```rust
use std::fs::File;
use std::io::{self, Read};

// 调用者得到一个Result进行处理
fn read_username_from_file() -> Result<String, io::Error> { 
    // 打开文件，f是`Result<文件句柄,io::Error>`
    let f = File::open("hello.txt");

    let mut f = match f {
        // 打开文件成功，将file句柄赋值给f
        Ok(file) => file,
        // 打开文件失败，将错误返回(向上传播)
        Err(e) => return Err(e),
    };
    // 创建动态字符串s
    let mut s = String::new();
    // 从f文件句柄读取数据并写入s中
    match f.read_to_string(&mut s) {
        // 读取成功，返回Ok封装的字符串
        Ok(_) => Ok(s),
        // 将错误向上传播
        Err(e) => Err(e),
    }
}

fn main() {
    let res = read_username_from_file();
    match res {
        Ok(s) => println!("{}", s),
        Err(e) => println!("{}", e),
    }
}
```

### ?操作符

#### Err传播

在上一节中对错误传播处理太麻烦，引入`?`操作符方便错误传播

`?`是一个宏，作用相当于以下代码，如果OK返回值，如果Err，返回Err继续向上传播
```rust
let mut f = match f {
    // 打开文件成功，将file句柄赋值给f
    Ok(file) => file,
    // 打开文件失败，将错误返回(向上传播)
    Err(e) => return Err(e),
};
```
上一届的代码可以优化成：
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?; //如果读取文件出错，上报Err
    let mut s = String::new();
    f.read_to_string(&mut s)?; // 如果从文件中读取字符串错误，上报Err
    Ok(s)
}
```

错误之间是有上下级关系，就像子类父类，`std::io::Error` 是`std::error::Error`的一种，`?`可以进行错误之间的隐式转换。只要实现了`From`特征，就可以实现从一种类型转成另一种类型。

```rust
fn open_file() -> Result<File, Box<dyn std::error::Error>> {
    let mut f = File::open("hello.txt")?;
    Ok(f)
}
```
`?`的链式调用
```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();

    File::open("hello.txt")?.read_to_string(&mut s)?;

    Ok(s)
}

use std::fs;
use std::io;

fn read_username_from_file() -> Result<String, io::Error> {
    // read_to_string是定义在std::io中的方法，因此需要在上面进行引用
    fs::read_to_string("hello.txt")
}
```

#### Option传播

Result 通过 ? 返回错误，那么 Option 就通过 ? 返回 None

```rust
fn first(arr: &[i32]) -> Option<&i32> {
   let v = arr.get(0)?;
   Some(v)
}

//等同于
fn first(arr: &[i32]) -> Option<&i32> {
   arr.get(0)
   arr.get(0)? //编译失败，调用？必须要有个变量承载返回值
}
```

#### 带返回值的main

```rust
use std::error::Error;
use std::fs::File;

fn main() -> Result<(), Box<dyn Error>> { //main可有返回值
    let f = File::open("hello.txt")?;

    Ok(())
}
```